image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0
  CI_DEBUG_TRACE: "true"

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_REMOTE_URL: ssh://dokku@116.203.96.104:22/rs
    SSH_PRIVATE_KEY: ${hetzer_server_ssh_private_key}
  script: dokku-deploy
    - echo ${hetzer_server_ssh_private_key}
  after_script: [dokku-unlock]
