image: dokku/ci-docker-image

stages:
  - deploy
  - test

variables:
  GIT_DEPTH: 0
  CI_DEBUG_TRACE: "true"
test:
  script:
    - echo xxxXXX${hetzer_server_ssh_private_key}
deploy:
  stage: deploy
  only:
    - main
  variables:
    GIT_REMOTE_URL: ssh://dokku@116.203.96.104:22/rs
    SSH_PRIVATE_KEY: ${hetzer_server_ssh_private_key}
  script: dokku-deploy

  after_script: [dokku-unlock]
